#!/usr/bin/python3
import sys


def factorization():
    try:
        r = sys.argv[1]
        with open(r) as fp:
            for r in fp:
                r = int(r)
                if r % 2 == 0:
                        print("{}={}*{}".format(r, r // 2, 2))
                        continue
                x = 3
                while x < r // 2:
                    if r % x == 0:
                        print("{}={}*{}".format(r, r // x, x))
                        break
                    x = x + 2
                if x == (r // 2) + 1:
                    print("{}={}*{}".format(r, r, 1))
    except (IndexError):
        pass
factorization()
