#!/usr/bin/python3
import sys

with open(argv[1]) as file:
    for line in file:
        num = int(line)
        print("{:d}=".format(num), end="")
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for i in range(3, num, 2):
            if num % i == 0:
                f = num//i
                for j in range(3, f, 2):
                    if f % j == 0 or i % j == 0:
                        break
                print("{}*{}".format(f, i))
                break
