#!/usr/bin/python3
import sys
import math

with open(sys.argv[1], "r") as fp:
    num = int(fp.readline())
    if num % 2 == 0:
        print("{}={}*{}".format(num, int(num / 2), 2))
    else:
        h = int(ceil(sqrt(num)))
        while (True):
            k1 = h * h - num
            k = int(sqrt(k1))
            if(k * k == k1):
                break
            else:
                h += 1
        print("{}={}*{}".format(num, h + k, h - k))
